language: node_js
node_js: "10"

script:
  - npm test
  - npm run build

deploy:
  provider: script
  script: npm run deploy
  skip_cleanup: true
  target_branch: master
  keep_history: true
  on:
    branch: master
